// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRXNbVkZZz1v1VOlvifpXQdYqxpVU4A3U',
    appId: '1:845415001684:android:f817de66e777d44b6407c1',
    messagingSenderId: '845415001684',
    projectId: 'sheraz-in-app-messaging-app',
    storageBucket: 'sheraz-in-app-messaging-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMEJYZq9xLm4P0mqLlXgSpDxQ5Ll6jti0',
    appId: '1:845415001684:ios:25e6185347c5fc986407c1',
    messagingSenderId: '845415001684',
    projectId: 'sheraz-in-app-messaging-app',
    storageBucket: 'sheraz-in-app-messaging-app.firebasestorage.app',
    iosClientId: '845415001684-daub1mp149gk4amvtoj5dievb3bs7eo3.apps.googleusercontent.com',
    iosBundleId: 'com.sherazapp.inappmessaging',
  );
}
